# $schema: https://json.schemastore.org/github-workflow.json

name: "_ Build _"

on:
  workflow_dispatch:
  workflow_call:
    outputs:
      digest_manifest:
        value: ${{ jobs.digests.outputs.manifest }}

jobs:
  build-linux:
    name: Linux
    runs-on: ubuntu-latest

    outputs:
      sha256: ${{ steps.digest.outputs.sha256 }}

    steps:
    - name: gitconfig
      run: |
        git config --global core.autocrlf input
      #        git config --global core.eol lf

    - name: Checkout
      uses: actions/checkout@v6

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        targets: x86_64-unknown-linux-gnu
        components: rustfmt, clippy

    - name: Setup cargo Cache
      uses: Swatinem/rust-cache@v2
      continue-on-error: false
      with:
        key: ${{ runner.os }}-cargo-${{ hashFiles('rustybits//Cargo.lock') }}
        shared-key: ${{ runner.os }}-cargo-
        workspaces: |
          rustybits/

    - name: make
      run: make

    - name: selftest
      run: |
        make selftest
        ./zerotier-selftest

    - name: Generate Digests
      id: digest
      run: |
        SHA256=$(sha256sum my_file.zip | awk '{print $1}')
        echo "sha256=$SHA256" >> "$GITHUB_OUTPUT"

    - name: Tar Builds
      run: tar -cvJf zerotier-one-linux.tar.xz zerotier-one

    - name: Upload Builds
      uses: actions/upload-artifact@v7
      with:
        path: zerotier-one-linux.tar.xz
        archive: false

  build-macos:
    name: MacOS
    runs-on: macos-latest

    outputs:
      sha256: ${{ steps.digest.outputs.sha256 }}

    steps:
    - name: gitconfig
      run: |
        git config --global core.autocrlf input
      #        git config --global core.eol lf

    - name: Checkout
      uses: actions/checkout@v6

    - name: Setup Rust (aarch64)
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        target: aarch64-apple-darwin
        components: rustfmt, clippy

    - name: Setup Rust (x86_64)
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        target: x86_64-apple-darwin
        components: rustfmt, clippy

    - name: Setup cargo Cache
      uses: Swatinem/rust-cache@v2
      continue-on-error: false
      with:
        key: ${{ runner.os }}-cargo-${{ hashFiles('rustybits//Cargo.lock') }}
        shared-key: ${{ runner.os }}-cargo-
        workspaces: |
          rustybits/

    - name: make
      run: make

    - name: selftest
      run: |
        make selftest
        ./zerotier-selftest

    - name: Generate Digests
      id: digest
      run: |
        SHA256=$(sha256sum my_file.zip | awk '{print $1}')
        echo "sha256=$SHA256" >> "$GITHUB_OUTPUT"

    - name: Tar Builds
      run: tar -cvJf zerotier-one-macos.tar.xz zerotier-one

    - name: Upload Builds
      uses: actions/upload-artifact@v7
      with:
        path: zerotier-one-macos.tar.xz
        archive: false

  build-windows:
    name: Windows
    runs-on: windows-latest

    outputs:
      sha256: ${{ steps.digest.outputs.sha256 }}

    steps:
    - name: gitconfig
      run: |
        git config --global core.autocrlf true
      #        git config --global core.eol lf

    - name: Checkout
      uses: actions/checkout@v6

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        targets: x86_64-pc-windows-msvc
        components: rustfmt, clippy

    - name: Setup cargo Cache
      uses: Swatinem/rust-cache@v2
      continue-on-error: false
      with:
        key: ${{ runner.os }}-cargo-${{ hashFiles('rustybits//Cargo.lock') }}
        shared-key: ${{ runner.os }}-cargo-
        workspaces: |
          rustybits/

    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v3

    - name: msbuild
      run: |
        msbuild windows\ZeroTierOne.sln /m /p:Configuration=Release /property:Platform=x64 /t:ZeroTierOne

    - name: Generate Digests
      id: digest
      shell: pwsh
      run: |
        $SHA256 = (Get-FileHash -Path "windows/Build/x64/Release/zerotier-one_x64.exe" -Algorithm SHA256).Hash
        echo "sha256=$SHA256" >> "$env:GITHUB_OUTPUT"

    - name: Tar Builds
      run: tar -cvJf zerotier-one-windows.tar.xz windows/Build/x64/Release/zerotier-one_x64.exe

    - name: Upload Builds
      uses: actions/upload-artifact@v7
      with:
        path: zerotier-one-windows.tar.xz
        archive: false

  digests:
    name: Generate Digests Manifest
    runs-on: ubuntu-latest

    needs:
      - build-linux
      - build-macos
      - build-windows

    outputs:
      manifest: ${{ steps.manifest.outputs.content }}

    steps:
      - id: manifest
        run: |
          echo "content<<EOF" >> "$GITHUB_OUTPUT"
          echo "linux: ${{ needs.build-linux.outputs.sha256 }}" >> "$GITHUB_OUTPUT"
          echo "macos: ${{ needs.build-macos.outputs.sha256 }}" >> "$GITHUB_OUTPUT"
          echo "windows: ${{ needs.build-windows.outputs.sha256 }}" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"
